### PR TITLE
Improve variable naming

### PR DESCRIPTION
**Pull request by Dinoosawruss**
[A brief description of what your PR intends to achieve.]
Re: #7 changing various variable names to improve understanding of what they do

Please complete these tasks before opening your PR:
- [x] My PR has been linted with flake8, i.e. `poetry run flake8`
- [x] My PR has been formatted with black, i.e. `poetry run black .`

### CODE REVIEW

**Comment by Dinoosawruss** [comment]
> `duration` -> `typing_duration`, but maybe it should be named `expected_typing_duration`
> `shuffle` -> `shuffle_flag`
> `term` -> `terminal` (I don't know if this improves the readability though, it makes an often used variable way too long, so many line breaks are introduced).
> `dir_path` -> `directory_name`
> `basedir` -> `base_directory`
> `wpm` -> `words_per_minute` (this is good, but maybe `typing_speed_in_wpm` is better?)

Sounds good I will keep these
As for `term` I think alone this is kinda confusing and it took me a minute to work out what it was referring to, not sure how it could improve shortness and ease of understanding
And I will change `words_per_minute` to `typing_speed_in_wpm` think that sounds better

**Comment by Dinoosawruss** [comment]
With the changes suggested I've ticked the ones I agree with, the ones that aren't ticked will have some comment below
* [x]  `typed_word_input` should stay `input`, because this can be a stream/tty/file

* [ ]  `words_list` doesn't really add to the explanation of the variable

* [x]  I prefer `chars` over `characters`

* [x]  I prefer colors names as they were, if you look at the commit history I had them named before as you put it, but they don't only color words

* [ ]  `time_passed` sounds better than `passed_duration` to me, but maybe it should be named `actual_typing_duration`, or just `typing_duration`

* [x]  `user_text` sounds better than just `text`, but I think we need a better name. That is the text that the user types before it is submitted as a word. I used to call it `typed_word` but it doesn't come off right in my opinion. I think it's best to leave it until we find a better name.

* [x]  I don't like the prefix `test` in front of word variables (I had initially named them like that but it was way too confusing later on. I'd keep `word` and change the `word_i` to `word_index`

`words_list` - not sure what else this could be that adds any sort of explanation? Any ideas?
`time_passed` - perhaps we could change it to `typing_duration`? I think the "actual" is slightly redundant

**Comment by Dinoosawruss** [comment]
I've resolved everything updated in https://github.com/MasterMedo/typetest/pull/22/commits/45b93b9a5694f1469c8a0dfa23831b8710393b8d and https://github.com/MasterMedo/typetest/pull/22/commits/a12ca72642869df87df2577b2dd63c1e2ec716e2

I noticed there are some conflicts with the master branch so I will resolve these now

**Comment by MasterMedo** [comment]
Thanks for improving typetest.

I appreciate your effort. 🥇

**Pull request merged**
